apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-backend-deployment
  namespace: default
spec:
  replicas: 2
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      
  selector:
    matchLabels:
      app: lms-backend
  template:
    metadata:
      labels:
        app: lms-backend
    spec:
      containers: # image aws_account_id: 변경사항 확인해보기
      - name: backend-container
        image: 879772956301.dkr.ecr.us-east-1.amazonaws.com/lms-backend:latest
   
        ports:
        - containerPort: 8080
        
        envFrom: # config와 secret name 확인해보기
        - configMapRef:
            name: lms-backend-config
        - secretRef:
            name: lms-backend-secret