apiVersion: v1
kind: Secret
metadata:
  name: lms-backend-secret
  namespace: default
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: "cG9zdGdyZXMudW5tbnpwZXBxdGpuanVlcXJha3k="
  
  SPRING_DATASOURCE_PASSWORD: "YWl2bGUyMDI2MDkhQCM="
  
  JWT_SECRET: "YWl2bGUtYm9va2FwcC1qd3Qtc2VjcmV0LWtleS1haXZsZS1ib29rYXBwLWp3dC1zZWNyZXQta2V5LTEyMzQ1Ng=="